### ISSUE TITLE
General questions regarding real-time C++

### ISSUE THREAD

**Issue by DerrickLau** [ckormanyos/real-time-cpp#52]
Thank you sir for producing such an excellent book for helping hobbyists like me understand a little about building real-time systems with microcontrollers.

I looked through the book and noticed that you had timings for some of your C++ methods.  How did you calculate how long those methods took to execute?  How did you confirm that those methods consistently took that amount of time to execute?  Did you have a special test tool or did you just add a real-time clock to your circuit and ran the same method multiple times to see if the execution times were consistent?  How does one calculate the length of time for a method to execute during the architecture phase?

**Comment by ckormanyos** [comment]
> How did you calculate how long those methods took to execute?

The times listed in the book are not calculated times, but rather measured times. The measurement technique used in most of these measurements is trivially simple. A digital port is toggled to high just prior to calling the sequence-to-be-measured and the same port is toggled low immediately following the sequence-to-be-measured. The resulting pulse is viewed and analyzed o´n a digital oscilloscope.

> How did you confirm that those methods consistently took that amount of time to execute?

It depends on the code sequence. Some code sequences have alomst no variance whatsoever in they do not have brances (if) and the like. These code sequences usually run in constant time. If a sequence has branches, then various inputs in a range can be used to measure a statistical distribution of the runtime. For very short sequences, global interrupts can also be disabled prior to the measurement and enabled afterwards. But the sequence must be short and remember to always activate interrupts following the measurement. These measurements should not be present in production code.

> Did you have a special test tool or did you just add a real-time clock to your circuit and ran the same method multiple times to see if the execution times were consistent?

You could in principle use either. In these simple measurements, a digital port toggle high and low has been used. If you intend to seup a digital real-time tick, you can use a free-running timer in the microcontroller peripherals. Start and stop times can be derived from a free-running timer. If you have access to the <chrono> header, yyou can build up a digital stopwatch with these functions. But you must ensure that chrono has an underlying tick in the system with fine granularity such as microseconds. There are several tools available on the market for real time measurements, but these can be too expensive for hobby domain.

> How does one calculate the length of time for a method to execute during the architecture phase?

If you are using a multitasking scheduler, you should familiarize yourself with peak and average cacle times and periods of each task in the multitasking scheduler. The same goes for interrupt run times.

Please feel to refine or extend the questions in this issue here, as needed.

In addition, in the book, see Sects. 9.6 and B.3 for further information on these topics.

Also, a runtime measurement in code can be found at the lines below:
[line 31](https://github.com/ckormanyos/real-time-cpp/blob/master/ref_app/src/app/benchmark/app_benchmark.cpp#L31)
[line 38](https://github.com/ckormanyos/real-time-cpp/blob/master/ref_app/src/app/benchmark/app_benchmark.cpp#L38)
[line 81](https://github.com/ckormanyos/real-time-cpp/blob/master/ref_app/src/app/benchmark/app_benchmark.cpp#L81)

Kind regards, Chris.
